language: cpp
compiler:
  - gcc
  - clang
before_script:
  - make clean
install: make deps
script:
  - make test && make
branches:
  only:
    - master
notifications:
  recipients:
    - tanel.lebedev@gmail.com
  email:
    on_success: change
    on_failure: always
before_install:
  - sudo apt-add-repository -y ppa:beineri/opt-qt531
  - sudo apt-get -qq update
  - sudo apt-get -qq install qt53tools qt53svg qt53webkit
