language: cpp
compiler:
  - gcc
  - clang
before_script:
  - make clean
install: make deps
script: make test
branches:
  only:
    - master
notifications:
  recipients:
    - tanel.lebedev@gmail.com
  email:
    on_success: change
    on_failure: always
