name: Linux Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: Build on Linux + tarball
      run: |
        sudo apt install libxss1 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 qt5-default libqt5gui5 libqt5webengine5 libqt5webenginecore5 libqt5webenginewidgets5 libqt5printsupport5 libqt5quickwidgets5 libqt5x11extras5 libxss1 
        sudo apt install cmake pkg-config qtbase5-dev qtwebengine5-dev libqt5x11extras5-dev  qtbase5-private-dev libssl-dev libxss-dev libxmu-dev
        bash ./src/ui/linux/package.sh

  build-mac:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Build on macOS
      run: |
        make deps
        make
        
  build-win32:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Build on Windows x86
      run: |
        MSBuild.exe src/ui/windows/TogglDesktop/TogglDesktop.sln /property:Configuration=Release /p:Platform="x86" /t:Clean,Build /restore
        
  build-win64:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Build on Windows x64
      run: |
        MSBuild.exe src/ui/windows/TogglDesktop/TogglDesktop.sln /property:Configuration=Release /p:Platform="x64" /t:Clean,Build /restore
