name: Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: Build on Linux + tarball
      run: |
        sudo apt install libxss1 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 qt5-default libqt5gui5 libqt5webengine5 libqt5webenginecore5 libqt5webenginewidgets5 libqt5printsupport5 libqt5quickwidgets5 libqt5x11extras5 libxss1 
        sudo apt install patchelf binutils cmake pkg-config qtbase5-dev qtwebengine5-dev libqt5x11extras5-dev  qtbase5-private-dev libssl-dev libxss-dev libxmu-dev
        bash ./src/ui/linux/package.sh
        
  build-ubuntu1604:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build on Linux + tarball
      run: |
        sudo apt install devscripts
        dch -D unstable --package "toggldesktop" -v $version "General bug fixes and improvements" -u low -M

        
  build-ubuntu1804:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build on Linux + tarball
      run: |
        sudo apt install devscripts
        dch -D unstable --package "toggldesktop" -v $version "General bug fixes and improvements" -u low -M

  build-mac:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Build on macOS
      run: |
        sed -i.bak "s/B227VTMZ94/''/" src/lib/osx/TogglDesktopLibrary.xcodeproj/project.pbxproj
        sed -i.bak "s/B227VTMZ94/''/" src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
        #make deps
        make
        
  build-win32:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Build on Windows x86
      run: |
        choco install nsis -y
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" src/ui/windows/TogglDesktop/TogglDesktop.sln /property:Configuration=Release /p:Platform="x86" /t:Clean,Build /restore
        cd src/ui/windows/
        makensis TogglDesktopInstaller-x86.nsi
        
  build-win64:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Build on Windows x64
      run: |
        choco install nsis -y
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" src/ui/windows/TogglDesktop/TogglDesktop.sln /property:Configuration=Release /p:Platform="x64" /t:Clean,Build /restore
        cd src/ui/windows/
        makensis TogglDesktopInstaller-x64.nsi
